source :rubygems

gem 'revelation'

# Template engines: comment one or more in for automatic
# support of your preferred template engine.
# gem 'builder' # For .builder templates
# gem 'liquid'  # For .liquid templates
# gem 'rdiscount' # For Markdown (.md) templates
# gem 'redcloth' # For Textile templates
# gem 'creole' # For Wiki markup
